### ISSUE TITLE
Didn't compile on 2.13

### ISSUE THREAD

**Issue by nplatonova** [cequence-io/openai-scala-client#2]
It needs to update  com.typesafe.play
according this issue https://github.com/playframework/playframework/issues/11082
at least it works with com.typesafe.play.play-ahc-ws-standalone 2.2.0-M3

**Comment by peterbanda** [comment]
Hi @nplatonova ,

Thankx for reporting the issue!

The compilation on Scala 2.13 works without a problem if you uncomment `scala-java8-compat` dependency override in `build.sbt`s:

```
dependencyOverrides ++= Seq(
  "org.scala-lang.modules" %% "scala-java8-compat" % "1.0.2"
)
```

I will make it automatic based on a Scala version provided. Btw. the playframework issue 11082 handles the very same problem.
