### ISSUE TITLE
Configure standard logging framework

### ISSUE THREAD

**Issue by phelps-sg** [cequence-io/openai-scala-client#21]
Currently, e.g. `openai-core/src/main/scala/io/cequence/openaiscala/service/OpenAIRetryServiceAdapter.scala` uses injected functions for logging, but this makes it difficult to configure logging in the end application.

It might be a good idea to use a standard logging framework.  Currently SLF4j is included as transitive dep, so we could use [scala-logging](https://github.com/lightbend-labs/scala-logging).

**Comment by peterbanda** [comment]
I use `scala-logging` at the app level... will think about it

**Comment by phelps-sg** [comment]
There are several advantages of using logging framework in a library:
1. Generating debug strings can sometimes be costly if they are not simple constant literals.  Typically we might use a formatted string to dump non-string values to output: e.g. 
~~~scala
logger.debug(s"queue head = ${queue.head}")
~~~
Generating this string will incur some overhead, since we need to access the queue, which ideally we would like to avoid unless debugging is enabled.  Logging frameworks such as scala-logging use lazy evaluation to ensure the string is only built if debug is enabled.  [This avoids polluting the  code with if statements](https://github.com/lightbend-labs/scala-logging#readme).
2. We can easily have different log levels for DEBUG, WARN, INFO etc.
3. We can configure asynchronous loggers which do not block waiting for log IO to complete (synchronous logging IO can easily kill scalability in a large complex app). 
4. When we are troubleshooting issues with the library that are difficult to isolate, the bug reporter can easily enable debug logging for openai-scala-client and include debug output in their ticket.
5.  Nearly all Java and Scala libraries and frameworks use standard logging frameworks, and so users of openai-scala-client will naturally expect logging output from the library to be configurable using one of the standard configuration

**Comment by peterbanda** [comment]
the lib `logback-classic` added
