### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by philipwhiuk** [cequence-io/openai-scala-client#32]
I know you're trying to stay as close to the OpenAI API as possible with your naming conventions etc, but has any thought been given to supporting multiple vendors in the future (currently just Azure AFAIK). It seems like it would be a fairly similar feature set (albeit not everything is supported).

**Comment by phelps-sg** [comment]
My application would also benefit from a universal abstraction layer, allowing different completion backends to be configured, in my case ChatGPT versus hugging face chat completion.  Similar to ODBC/JDBC, different drivers could be installed depending on which backend provider is required by the application.

**Comment by peterbanda** [comment]
Yes, in progress! Azure, FastChat, and custom-URL APIs will be supported.. probably next week. Stay tuned.
