### ISSUE TITLE
Build fails with Type Error for Scala 3.2.2

### ISSUE THREAD

**Issue by phelps-sg** [cequence-io/openai-scala-client#37]
When building with:

~~~bash
sbt ++3.2.2 clean testWithCoverage
~~~

[error] -- [E170] Type Error: /home/sphelps/vcs/coding/openai-scala-client/openai-guice/src/main/scala/io/cequence/openaiscala/service/GuiceContainer.scala:20:60 
[error] 20 |  protected def instance[T: Manifest]: T = injector.instance[T]
[error]    |                                           ^^^^^^^^^^^^^^^^^^^^
[error]    |                                           T is not a class type
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from GuiceContainer.scala:20
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from GuiceContainer.scala:20
[error]     ----------------------------------------------------------------------------
[warn] there were 5 deprecation warnings; re-run with -deprecation for details
[warn] two warnings found
[error] one error found
[warn] one warning found
[error] (guice / Compile / compileIncremental) Compilation failed
[error] Total time: 14 s, completed 18 Jun 2023, 13:59:32
~~~

**Comment by peterbanda** [comment]
Fixed
