### ISSUE TITLE
Missing ability to count tokens before sending a query

### ISSUE THREAD

**Issue by piotrkuczko** [cequence-io/openai-scala-client#40]
Is it possible to add a functionality to this library that counts tokens prior to sending a query to ChatGPT? It would be beneficial to have such a feature, as it could allow the correct model - either gpt-3.5-turbo or gpt-3.5-turbo-16k - to be set before submitting the request. This can be achieved using the [JTokkit](https://github.com/knuddelsgmbh/jtokkit) library. An example of this implementation can be found [here](https://community.openai.com/t/how-to-calculate-the-tokens-when-using-function-call/266573/9).

**Comment by peterbanda** [comment]
Hey @piotrkuczko ,
Thanx for the suggestion. The lib looks solid. Will add it to my list.

**Comment by piotrkuczko** [comment]
PR -> https://github.com/cequence-io/openai-scala-client/pull/43
