### ISSUE TITLE
Extensions to use other GPT models and scaffold scala projects

### ISSUE THREAD

**Issue by joesan** [cequence-io/openai-scala-client#44]
Can this be extended to use other models? I'm sure it can as it is just a wrapper around a GPT API. Correct?

I have been recently exploring MetaGPT and it looks awesome. It has build agents that mimics the role of a person in a typical software company and it does generate everything sequentially. I kind of liked that idea. With a little bit of tweaking, it can be adapted to generate a Scala codebase. Is this something that this project will also attempt to do?

**Comment by peterbanda** [comment]
Hi @joesan, thanks for the suggestion!

The idea of having GPT agents is something quite useful (and trendy) but it goes beyond the scope of the project. We, however, explored the basic concept of GPT agents (in Scala) a few months ago in a separate project: https://github.com/cequence-io/babyagi-s (the port of babyAGI). You can take a look there.
