### ISSUE TITLE
Missing response_format option

### ISSUE THREAD

**Issue by SunPj** [cequence-io/openai-scala-client#46]
Lack of open AI's `response_format`  supports

**Comment by peterbanda** [comment]
it's in [CreateChatCompletionSettings](https://github.com/cequence-io/openai-scala-client/blob/master/openai-core/src/main/scala/io/cequence/openaiscala/domain/settings/CreateChatCompletionSettings.scala) - `response_format_type`

**Comment by SunPj** [comment]
@peterbanda Those changes were added on Nov 14, while the last release 0.5.0 from October 3 doesn't have the changes. Can we make a new release with the latest changes?

**Comment by peterbanda** [comment]
Just released the version `1.0.0.RC.1`. Enjoy!
