### ISSUE TITLE
OpenAIServiceStreamedFactory need support  FastChat service?

### ISSUE THREAD

**Issue by Xu-Chen** [cequence-io/openai-scala-client#47]
thank you

**Comment by peterbanda** [comment]
Have had it locally for a while. Will commit

**Comment by peterbanda** [comment]
Use it as `OpenAICoreServiceStreamedFactory.customInstance("http://localhost:8000/v1/")` or `OpenAIServiceStreamedFactory.customInstance("http://localhost:8000/v1/")`

**Comment by Xu-Chen** [comment]
Amazing！！
 Thank you very much，and when is it planned to be released?

**Comment by Xu-Chen** [comment]
> Use it as `OpenAICoreServiceStreamedFactory.customInstance("http://localhost:8000/v1/")` or `OpenAIServiceStreamedFactory.customInstance("http://localhost:8000/v1/")`

@peterbanda  Thank you very much，and when is it planned to be released?

**Comment by peterbanda** [comment]
Just released the version `1.0.0.RC.1`. Enjoy!
