### ISSUE TITLE
Implement model router for "Streamed" service

### ISSUE THREAD

**Issue by yahor-filipchyk** [cequence-io/openai-scala-client#67]
Currently the `OpenAIServiceAdapters#chatCompletionRouter` only works with instances of type `OpenAIChatCompletionService`. It would be nice also to have a router for `OpenAIChatCompletionStreamedServiceExtra`.

I am looking to add Anthropic to the list of supported models. Most of our user experiences require streaming. Since `OpenAIAnthropicChatCompletionService` already implements both `OpenAIAnthropicChatCompletionService` and `OpenAIChatCompletionStreamedServiceExtra` I imagine it wouldn't be hard to support model routing for streamed requests?

**Comment by peterbanda** [comment]
Hey @yahor-filipchyk , it's definitely possible! Check out these two examples:

- [ChatCompletionStreamedRouterWithFullServiceExample](https://github.com/cequence-io/openai-scala-client/blob/master/openai-examples/src/main/scala/io/cequence/openaiscala/examples/adapter/ChatCompletionStreamedRouterWithFullServiceExample.scala)
- [ChatCompletionStreamedRouterWithMappedModelsExample](https://github.com/cequence-io/openai-scala-client/blob/master/openai-examples/src/main/scala/io/cequence/openaiscala/examples/adapter/ChatCompletionStreamedRouterWithMappedModelsExample.scala)

I agree it would be better to incorporate the routing of streaming functions to `adapters` abstraction. It's on my list :)

**Comment by yahor-filipchyk** [comment]
@peterbanda perfect! Didn't realize `OpenAIChatCompletionStreamedServiceRouter` was already available!
