### ISSUE TITLE
Using non gemini models with Vertex-AI

### ISSUE THREAD

**Issue by antonio-veezoo** [cequence-io/openai-scala-client#79]
Vertex-AI has many models available through their platform (https://cloud.google.com/model-garden) not just gemini models. Is there a way to access them with this library? Is adding a new model to list of NonOpenAIModels an involved process or is the list there just for people not to have to look around to find the model's strings?

Thanks for any info!

**Comment by peterbanda** [comment]
Hey @antonio-veezoo , `NonOpenAIModels` are far from being exhaustive and are meant more less as "bookmarks". A caller can actually pass any model id (`String`) to chat completion that is known to be supported by a requested provider (in your case Vertex AI/Google). Anyway I will add a couple more models ids from the link you provided.

Thanx for the heads up.
