### ISSUE TITLE
appears to be using non-daemon threads

### ISSUE THREAD

**Issue by senecaso** [cequence-io/openai-scala-client#8]
When my application exits, a number of threads with the prefix `AsyncHttpClient` are left running.  Since these threads are not daemon threads, and there doesn't appear to be any way to `close()` the `OpenAIService` instance, the JVM hangs on exit.  Either need to expose a way to dispose of these resources when they are no longer needed, or switch to using daemon threads so they don't block the JVM on exit.

**Comment by peterbanda** [comment]
Hey @senecaso,

Sure thing! I was planing to expose `close()` function anyway. Will do it in the next version.

Cheers,
Peter
