### ISSUE TITLE
Any plans to support caching for either Anthropic or VertexAI?

### ISSUE THREAD

**Issue by antonio-veezoo** [cequence-io/openai-scala-client#85]
Does the library currently support caching for these providers in any way or do you have plans to add support?

Thanks for any info!

**Comment by peterbanda** [comment]
Hey @antonio-veezoo ,

could you elaborate a bit? What kind of caching do you have in mind - prompt, context, etc

**Comment by antonio-veezoo** [comment]
I'm thinking of the functionality described here for Calude https://www.anthropic.com/news/prompt-caching, and here for gemini https://cloud.google.com/vertex-ai/generative-ai/docs/context-cache/context-cache-overview

**Comment by peterbanda** [comment]
ok, we can do the prompt caching for Anthropic models (was on our list anyway)

**Comment by peterbanda** [comment]
@antonio-veezoo done! Claude prompt caching is now supported. Will be published with the version 1.1.1

**Comment by antonio-veezoo** [comment]
@peterbanda Thank you very much! Caching helps us out a lot in reducing per query cost.
