### ISSUE TITLE
Dynamic Token Assignment

### ISSUE THREAD

**Issue by ZinoviiZ** [cequence-io/openai-scala-client#86]
Is there any way to specify the OpenAI token per request (for example, chat completion) instead of creating a factory for each token that needs to be closed after the request?

The use case is that I want to have a single instance of the service but dynamically select different tokens for different requests.

Thanks!

**Comment by peterbanda** [comment]
Hey @ZinoviiZ ,

If you want to "hide" multiple services, you can use the round-robin or random-order adapters (see `RoundRobinAdapterExample` and `RandomOrderAdapterExample`). If you need to perform mapping, currently only model-to-service mapping is supported using the router adapter—see `ChatCompletionRouterAdapterWithMappedModelsExample`. In this case, you would need to encode the "tokens" in the model name, and all tokens would need to be known at the time of creation. Other than that, you can always code your custom adapter and override/wrap just `createChatCompletion` function.

Cheers,
Peter
